# This workflow will do a clean installation of node dependencies, lint, migrate the database, and build the source code.
# For more information, see: https://docs.github.com/en/actions/automating-builds-and-tests/building-and-testing-nodejs

name: lint-migrate-build

on: [push, pull_request]

jobs:
  lint-migrate-build:
    runs-on: ubuntu-latest

    strategy:
      matrix:
        node-version: [18.x, 20.x, 22.x]
        # See supported Node.js release schedule at https://nodejs.org/en/about/releases/

    steps:
      - uses: actions/checkout@v4
      - name: Use Node.js ${{ matrix.node-version }}
        uses: actions/setup-node@v4
        with:
          node-version: ${{ matrix.node-version }}
          cache: "npm"

      - name: Install dependencies
        run: |
          npm ci
          cd frontend && npm ci
          cd ../backend && npm ci

      - name: Lint project
        run: |
          npm run lint-frontend
          npm run lint-backend

      - name: Create backend env file
        run: |
          cd backend
          touch .env
          echo "DATABASE_URL="postgres://bb6:bb6@localhost:5432/notetube_dev?sslmode=disable"" >> .env

      - name: Migrate table schemas to local database
        run: npm run migrate-up

      - name: Build frontend
        run: npm run build-frontend
